exclude: ['README.markdown', 'Gemfile.lock', 'Gemfile']
url: http://bezet.outoftheblue.pl
markdown: redcarpet
#redcarpet:
#      extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
